export default [
    {
        "surat_number": 1,
        "juzz": "الجزء Tumbutere 1",
        "surat": "سورة الفاتحة Simoore Udditirnde",
        "juzz_number": 1,
        "ar_title": "الفاتحة",
        "pr_title": "Udditirnde",
        "ayat_number": 7,
        "ayat_img": require("./images/ayat/7.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/1_Fatiha.mp3",
        "page_number": 1,
        "size": 1308,
        "ayats_list": require("./ayats/1-faatih")
    },
    {
        "surat_number": 40,
        "juzz": "الجزء Tumbutere 24",
        "surat": "سورة غافر Simoore Jaafotooɗo",
        "juzz_number": 24,
        "ar_title": "غافر",
        "pr_title": "Jaafotooɗo",
        "ayat_number": 85,
        "ayat_img": require("./images/ayat/85.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/40_AlGaafir.mp3",
        "page_number": 40,
        "size": 56184,
        "ayats_list": require("./ayats/40-ghaafir")
    },
    {
        "surat_number": 41,
        "juzz": "الجزء Tumbutere 24",
        "surat": "سورة فصلت Simoore Ceerndugol",
        "juzz_number": 24,
        "ar_title": "فصلت",
        "pr_title": "Ceerndugol",
        "ayat_number": 54,
        "ayat_img": require("./images/ayat/54.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/41_FusSilat.mp3",
        "page_number": 41,
        "size": 39808,
        "ayats_list": require("./ayats/41-fussilaat")
    },
    {
        "surat_number": 42,
        "juzz": "الجزء Tumbutere 25",
        "surat": "سورة الشورى Simoore Diisnondiral",
        "juzz_number": 25,
        "ar_title": "الشورى",
        "pr_title": "Diisnondiral",
        "ayat_number": 53,
        "ayat_img": require("./images/ayat/53.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/42_AsSuura.mp3",
        "page_number": 42,
        "size": 43056,
        "ayats_list": require("./ayats/42-as-shuuraa")
    },
    {
        "surat_number": 43,
        "juzz": "الجزء Tumbutere 25",
        "surat": "سورة الزخرف Simoore Cuɗaari",
        "juzz_number": 25,
        "ar_title": "الزخرف",
        "pr_title": "Cuɗaari",
        "ayat_number": 89,
        "ayat_img": require("./images/ayat/89.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/43_AzZoukhraf.mp3",
        "page_number": 43,
        "size": 41792,
        "ayats_list": require("./ayats/43-az-zukhruf")
    },
    {
        "surat_number": 44,
        "juzz": "الجزء Tumbutere 25",
        "surat": "سورة الدخان Simoore Cuurki",
        "juzz_number": 25,
        "ar_title": "الدخان",
        "pr_title": "Cuurki",
        "ayat_number": 59,
        "ayat_img": require("./images/ayat/59.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/44_AdDukhan.mp3",
        "page_number": 44,
        "size": 18192,
        "ayats_list": require("./ayats/44-ad-dukhaan")
    },
    {
        "surat_number": 45,
        "juzz": "الجزء Tumbutere 25",
        "surat": "سورة الجاثية Simoore Dicciiɗo",
        "juzz_number": 25,
        "ar_title": "الجاثية",
        "pr_title": "Dicciiɗo",
        "ayat_number": 37,
        "ayat_img": require("./images/ayat/37.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/45_AlJaasiyatou.mp3",
        "page_number": 45,
        "size": 22852,
        "ayats_list": require("./ayats/45-al-jashiya")
    },
    {
        "surat_number": 46,
        "juzz": "الجزء Tumbutere 26",
        "surat": "سورة الأحقاف Simoore Luggere",
        "juzz_number": 26,
        "ar_title": "الأحقاف",
        "pr_title": "Luggere",
        "ayat_number": 35,
        "ayat_img": require("./images/ayat/35.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/46_AlAhqaaf.mp3",
        "page_number": 46,
        "size": 31128,
        "ayats_list": require("./ayats/46-al-ahqaaf")
    },
    {
        "surat_number": 47,
        "juzz": "الجزء Tumbutere 26",
        "surat": "سورة محمد Simoore Muhammadu",
        "juzz_number": 26,
        "ar_title": "محمد",
        "pr_title": "Muhammadu",
        "ayat_number": 38,
        "ayat_img": require("./images/ayat/38.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/47_Mouhammad.mp3",
        "page_number": 47,
        "size": 26380,
        "ayats_list": require("./ayats/47-muhammad")
    },
    {
        "surat_number": 48,
        "juzz": "الجزء Tumbutere 26",
        "surat": "سورة الفتح Simoore Udditaare",
        "juzz_number": 26,
        "ar_title": "الفتح",
        "pr_title": "Udditaare",
        "ayat_number": 29,
        "ayat_img": require("./images/ayat/29.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/48_AlFathi.mp3",
        "page_number": 48,
        "size": 25852,
        "ayats_list": require("./ayats/48-al-fath")
    },
    {
        "surat_number": 49,
        "juzz": "الجزء Tumbutere 26",
        "surat": "سورة الحجرات Simoore Cuuɗi",
        "juzz_number": 26,
        "ar_title": "الحجرات",
        "pr_title": "Cuuɗi",
        "ayat_number": 18,
        "ayat_img": require("./images/ayat/18.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/49_AlHujuraat.mp3",
        "page_number": 49,
        "size": 17252,
        "ayats_list": require("./ayats/49-al-hujuraat")
    },
    {
        "surat_number": 50,
        "juzz": "الجزء Tumbutere 26",
        "surat": "سورة ق Simoore Qaaf",
        "juzz_number": 26,
        "ar_title": "ق",
        "pr_title": "Qaaf",
        "ayat_number": 45,
        "ayat_img": require("./images/ayat/45.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/50_Qaaf.mp3",
        "page_number": 50,
        "size": 17124,
        "ayats_list": require("./ayats/50-qaaf")
    },
    {
        "surat_number": 51,
        "juzz": "الجزء Tumbutere 26",
        "surat": "سورة الذاريات Simoore Carkitooji",
        "juzz_number": 26,
        "ar_title": "الذاريات",
        "pr_title": "Carkitooji",
        "ayat_number": 60,
        "ayat_img": require("./images/ayat/60.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/51_AzZariyat.mp3",
        "page_number": 51,
        "size": 17152,
        "ayats_list": require("./ayats/51-az-zaariyat")
    },
    {
        "surat_number": 52,
        "juzz": "الجزء Tumbutere 27",
        "surat": "سورة الطور Simoore Haayre Tulliniinde",
        "juzz_number": 27,
        "ar_title": "الطور",
        "pr_title": "Haayre Tulliniinde",
        "ayat_number": 49,
        "ayat_img": require("./images/ayat/49.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/52_AtTuuri.mp3",
        "page_number": 52,
        "size": 16436,
        "ayats_list": require("./ayats/52-at-tuur")
    },
    {
        "surat_number": 53,
        "juzz": "الجزء Tumbutere 27",
        "surat": "سورة النجم Simoore Hoodere",
        "juzz_number": 27,
        "ar_title": "النجم",
        "pr_title": "Hoodere",
        "ayat_number": 62,
        "ayat_img": require("./images/ayat/62.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/53_AnNajmi.mp3",
        "page_number": 53,
        "size": 17280,
        "ayats_list": require("./ayats/53-an-najm")
    },
    {
        "surat_number": 54,
        "juzz": "الجزء Tumbutere 27",
        "surat": "سورة القمر Simoore Lewru",
        "juzz_number": 27,
        "ar_title": "القمر",
        "pr_title": "Lewru",
        "ayat_number": 55,
        "ayat_img": require("./images/ayat/55.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/54_AlQamari.mp3",
        "page_number": 54,
        "size": 17532,
        "ayats_list": require("./ayats/54-al-qamar")
    },
    {
        "surat_number": 55,
        "juzz": "الجزء Tumbutere 27",
        "surat": "سورة الرحمن Simoore Jurumdeero",
        "juzz_number": 27,
        "ar_title": "الرحمن",
        "pr_title": "Jurumdeero",
        "ayat_number": 78,
        "ayat_img": require("./images/ayat/78.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/55_AlRahman.mp3",
        "page_number": 55,
        "size": 22296,
        "ayats_list": require("./ayats/55-ar-rahmaan")
    },
    {
        "surat_number": 56,
        "juzz": "الجزء Tumbutere 27",
        "surat": "سورة الواقعة Simoore Ñalngu Ñaawoore",
        "juzz_number": 27,
        "ar_title": "الواقعة",
        "pr_title": "Ñalngu Ñaawoore",
        "ayat_number": 96,
        "ayat_img": require("./images/ayat/96.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/56_AlWaqiah.mp3",
        "page_number": 56,
        "size": 22856,
        "ayats_list": require("./ayats/56-al-waqiat")
    },
    {
        "surat_number": 57,
        "juzz": "الجزء Tumbutere 27",
        "surat": "سورة الحديد Simoore Njamndi",
        "juzz_number": 27,
        "ar_title": "الحديد",
        "pr_title": "Njamndi",
        "ayat_number": 29,
        "ayat_img": require("./images/ayat/29.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/57_AlHadiidi.mp3",
        "page_number": 57,
        "size": 28472,
        "ayats_list": require("./ayats/57-al-hadid")
    },
    {
        "surat_number": 58,
        "juzz": "الجزء Tumbutere 28",
        "surat": "سورة المجادلة Simoore Coŋkondiral",
        "juzz_number": 28,
        "ar_title": "المجادلة",
        "pr_title": "Coŋkondiral",
        "ayat_number": 22,
        "ayat_img": require("./images/ayat/22.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/58_AlMujadila.mp3",
        "page_number": 58,
        "size": 23104,
        "ayats_list": require("./ayats/58-al-mujaadalah")
    },
    {
        "surat_number": 59,
        "juzz": "الجزء Tumbutere 28",
        "surat": "سورة الحشر Simoore Fergo",
        "juzz_number": 28,
        "ar_title": "الحشر",
        "pr_title": "Fergo",
        "ayat_number": 24,
        "ayat_img": require("./images/ayat/24.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/59_AlHasri.mp3",
        "page_number": 59,
        "size": 21868,
        "ayats_list": require("./ayats/59-al-hasr")
    },
    {
        "surat_number": 60,
        "juzz": "الجزء Tumbutere 28",
        "surat": "سورة الممتحنة Simoore Ƴeewndaaɗo",
        "juzz_number": 28,
        "ar_title": "الممتحنة",
        "pr_title": "Ƴeewndaaɗo",
        "ayat_number": 13,
        "ayat_img": require("./images/ayat/13.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/60_AlMumtahinatu.mp3",
        "page_number": 60,
        "size": 17156,
        "ayats_list": require("./ayats/60-al-mumtahanah")
    },
    {
        "surat_number": 61,
        "juzz": "الجزء Tumbutere 28",
        "surat": "سورة الصف Simoore Gorol",
        "juzz_number": 28,
        "ar_title": "الصف",
        "pr_title": "Gorol",
        "ayat_number": 14,
        "ayat_img": require("./images/ayat/14.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/61_AsSaffi.mp3",
        "page_number": 61,
        "size": 10460,
        "ayats_list": require("./ayats/61-as-saff")
    },
    {
        "surat_number": 62,
        "juzz": "الجزء Tumbutere 28",
        "surat": "سورة الجمعة Simoore Mawnde",
        "juzz_number": 28,
        "ar_title": "الجمعة",
        "pr_title": "Mawnde",
        "ayat_number": 11,
        "ayat_img": require("./images/ayat/11.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/62_AlJuma.mp3",
        "page_number": 62,
        "size": 8808,
        "ayats_list": require("./ayats/62-al-jumua")
    },
    {
        "surat_number": 63,
        "juzz": "الجزء Tumbutere 28",
        "surat": "سورة المنافقون Simoore Naafigeeɓe",
        "juzz_number": 28,
        "ar_title": "المنافقون",
        "pr_title": "Naafigeeɓe",
        "ayat_number": 11,
        "ayat_img": require("./images/ayat/11.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/63_AlMounafiqoun.mp3",
        "page_number": 63,
        "size": 9088,
        "ayats_list": require("./ayats/63-al-munafiqun")
    },
    {
        "surat_number": 64,
        "juzz": "الجزء Tumbutere 28",
        "surat": "سورة التغابن Simoore Waasre",
        "juzz_number": 28,
        "ar_title": "التغابن",
        "pr_title": "Waasre",
        "ayat_number": 18,
        "ayat_img": require("./images/ayat/18.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/64_AtTagabun.mp3",
        "page_number": 64,
        "size": 12096,
        "ayats_list": require("./ayats/64-at-taghabun")
    },
    {
        "surat_number": 65,
        "juzz": "الجزء Tumbutere 28",
        "surat": "سورة الطلاق Simoore Ceergal",
        "juzz_number": 28,
        "ar_title": "الطلاق",
        "pr_title": "Ceergal",
        "ayat_number": 12,
        "ayat_img": require("./images/ayat/12.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/65_AtTalaaqi.mp3",
        "page_number": 65,
        "size": 14508,
        "ayats_list": require("./ayats/65-at-talaaq")
    },
    {
        "surat_number": 66,
        "juzz": "الجزء Tumbutere 28",
        "surat": "سورة التحريم Simoore Haɗiinde",
        "juzz_number": 29,
        "ar_title": "التحريم",
        "pr_title": "Haɗiinde",
        "ayat_number": 12,
        "ayat_img": require("./images/ayat/12.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/66_AtTahrimi.mp3",
        "page_number": 66,
        "size": 16544,
        "ayats_list": require("./ayats/66-at-tahrim")
    },
    {
        "surat_number": 67,
        "juzz": "الجزء Tumbutere 29",
        "surat": "سورة الملك Simoore Laamateeri",
        "juzz_number": 29,
        "ar_title": "الملك",
        "pr_title": "Laamateeri",
        "ayat_number": 30,
        "ayat_img": require("./images/ayat/30.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/67_AlMoulki.mp3",
        "page_number": 67,
        "size": 16544,
        "ayats_list": require("./ayats/67-al-mulk")
    },
    {
        "surat_number": 68,
        "juzz": "الجزء Tumbutere 29",
        "surat": "سورة القلم Simoore Binndirgal",
        "juzz_number": 29,
        "ar_title": "القلم",
        "pr_title": "Binndirgal",
        "ayat_number": 52,
        "ayat_img": require("./images/ayat/52.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/68_AlQalam.mp3",
        "page_number": 68,
        "size": 15596,
        "ayats_list": require("./ayats/68-al-qalam")
    },
    {
        "surat_number": 69,
        "juzz": "الجزء Tumbutere 29",
        "surat": "سورة الحاقة Simoore Jojjinoore",
        "juzz_number": 29,
        "ar_title": "الحاقة",
        "pr_title": "Jojjinoore",
        "ayat_number": 52,
        "ayat_img": require("./images/ayat/52.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/69_AlHaqqah.mp3",
        "page_number": 69,
        "size": 13320,
        "ayats_list": require("./ayats/69-al-haaqqah")
    },
    {
        "surat_number": 70,
        "juzz": "الجزء Tumbutere 29",
        "surat": "سورة المعارج Simoore Ŋabbirɗe",
        "juzz_number": 29,
        "ar_title": "المعارج",
        "pr_title": "Ŋabbirɗe",
        "ayat_number": 44,
        "ayat_img": require("./images/ayat/44.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/70_AlMaarij.mp3",
        "page_number": 70,
        "size": 10796,
        "ayats_list": require("./ayats/70-al-maarij")
    },
    {
        "surat_number": 71,
        "juzz": "الجزء Tumbutere 29",
        "surat": "سورة نوح Simoore Nuuhu",
        "juzz_number": 29,
        "ar_title": "نوح",
        "pr_title": "Nuuhu",
        "ayat_number": 28,
        "ayat_img": require("./images/ayat/28.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/71_Nouh.mp3",
        "page_number": 71,
        "size": 10976,
        "ayats_list": require("./ayats/71-nuuh")
    },
    {
        "surat_number": 72,
        "juzz": "الجزء Tumbutere 29",
        "surat": "سورة الجن Simoore Konndoroŋaaji",
        "juzz_number": 29,
        "ar_title": "الجن",
        "pr_title": "Konndoroŋaaji",
        "ayat_number": 28,
        "ayat_img": require("./images/ayat/28.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/72_AlJinn.mp3",
        "page_number": 72,
        "size": 8632,
        "ayats_list": require("./ayats/72-al-jinn")
    },
    {
        "surat_number": 73,
        "juzz": "الجزء Tumbutere 29",
        "surat": "سورة المزمل Simoore Mojiiɗo/Cuddiiɗo",
        "juzz_number": 29,
        "ar_title": "المزمل",
        "pr_title": "Mojiiɗo/Cuddiiɗo",
        "ayat_number": 20,
        "ayat_img": require("./images/ayat/20.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/73_AlMouzammil.mp3",
        "page_number": 73,
        "size": 6728,
        "ayats_list": require("./ayats/73-al-muzamil")
    },
    {
        "surat_number": 74,
        "juzz": "الجزء Tumbutere 29",
        "surat": "سورة المدثر Simoore Cuddiiɗo",
        "juzz_number": 29,
        "ar_title": "المدثر",
        "pr_title": "Cuddiiɗo",
        "ayat_number": 56,
        "ayat_img": require("./images/ayat/56.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/74_AlMouddassir.mp3",
        "page_number": 74,
        "size": 9164,
        "ayats_list": require("./ayats/74-al-mushir")
    },
    {
        "surat_number": 75,
        "juzz": "الجزء Tumbutere 29",
        "surat": "سورة القيامة Simoore Darnga",
        "juzz_number": 29,
        "ar_title": "القيامة",
        "pr_title": "Darnga",
        "ayat_number": 40,
        "ayat_img": require("./images/ayat/40.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/75_AlQiyamah.mp3",
        "page_number": 75,
        "size": 8520,
        "ayats_list": require("./ayats/75-al-qiyamah")
    },
    {
        "surat_number": 76,
        "juzz": "الجزء Tumbutere 29",
        "surat": "سورة الانسان Simoore Neɗɗo",
        "juzz_number": 29,
        "ar_title": "الانسان",
        "pr_title": "Neɗɗo",
        "ayat_number": 31,
        "ayat_img": require("./images/ayat/31.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/76_AlInsan.mp3",
        "page_number": 76,
        "size": 8136,
        "ayats_list": require("./ayats/76-al-insaan")
    },
    {
        "surat_number": 77,
        "juzz": "الجزء Tumbutere 29",
        "surat": "سورة المرسلات Simoore Nulaateeɗi",
        "juzz_number": 29,
        "ar_title": "المرسلات",
        "pr_title": "Nulaateeɗi",
        "ayat_number": 50,
        "ayat_img": require("./images/ayat/50.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/77_AlMoursalat.mp3",
        "page_number": 77,
        "size": 7216,
        "ayats_list": require("./ayats/77-al-mursalat")
    },
    {
        "surat_number": 78,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة النباء Simoore Kumpitaali",
        "juzz_number": 30,
        "ar_title": "النباء",
        "pr_title": "Kumpitaali",
        "ayat_number": 40,
        "ayat_img": require("./images/ayat/40.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/78_AlNaba.mp3",
        "page_number": 78,
        "size": 5856,
        "ayats_list": require("./ayats/78-an-naba")
    },
    {
        "surat_number": 79,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة النازعات Simoore Ɗoofooji",
        "juzz_number": 30,
        "ar_title": "النازعات",
        "pr_title": "Ɗoofooji/Ɗuggitooji",
        "ayat_number": 46,
        "ayat_img": require("./images/ayat/46.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/79_AlAnNaziat.mp3",
        "page_number": 79,
        "size": 6156,
        "ayats_list": require("./ayats/79-an-naaziat")
    },
    {
        "surat_number": 80,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة عبس Simoore Ɗuurnaare",
        "juzz_number": 30,
        "ar_title": "عبس",
        "pr_title": "Ɗuurnaare",
        "ayat_number": 42,
        "ayat_img": require("./images/ayat/42.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/80_AlAbasa.mp3",
        "page_number": 80,
        "size": 4820,
        "ayats_list": require("./ayats/80-abasa")
    },
    {
        "surat_number": 81,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة التكوير Simoore Fiilaama Niɓɓere",
        "juzz_number": 30,
        "ar_title": "التكوير",
        "pr_title": "Fiilaama Niɓɓere",
        "ayat_number": 29,
        "ayat_img": require("./images/ayat/29.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/81_AlTakwir.mp3",
        "page_number": 81,
        "size": 4600,
        "ayats_list": require("./ayats/81-at-takwiir")
    },
    {
        "surat_number": 82,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الإنفطار Simoore Pusgol",
        "juzz_number": 30,
        "ar_title": "الإنفطار",
        "pr_title": "Pusgol",
        "ayat_number": 19,
        "ayat_img": require("./images/ayat/19.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/82_AlInfitar.mp3",
        "page_number": 82,
        "size": 3244,
        "ayats_list": require("./ayats/82-al-infitaar")
    },
    {
        "surat_number": 83,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة المطففين Simoore ŋosooɓe",
        "juzz_number": 30,
        "ar_title": "المطففين",
        "pr_title": "Ŋosooɓe/ŋakkinooɓe",
        "ayat_number": "36",
        "ayat_img": require("./images/ayat/36.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/83_AlMoutafifin.mp3",
        "page_number": 83,
        "size": 6580,
        "ayats_list": require("./ayats/83-al-mutaffifuun")
    },
    {
        "surat_number": 84,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الإنشقاق Simoore Seekannde",
        "juzz_number": 30,
        "ar_title": "الإنشقاق",
        "pr_title": "Seekannde/Feecannde",
        "ayat_number": 25,
        "ayat_img": require("./images/ayat/25.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/84_AlInchiqaq.mp3",
        "page_number": 84,
        "size": 3780,
        "ayats_list": require("./ayats/84-al-insiqaaq")
    },
    {
        "surat_number": 85,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة البروج Simoore Ɗaccuki",
        "juzz_number": 30,
        "ar_title": "البروج",
        "pr_title": "Ɗaccuki/Ñukkalnde koode ",
        "ayat_number": 22,
        "ayat_img": require("./images/ayat/22.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/85_AlBourouj.mp3",
        "page_number": 85,
        "size": 3812,
        "ayats_list": require("./ayats/85-al-buruuj")
    },
    {
        "surat_number": 86,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الطارق Simoore Roƴoore",
        "juzz_number": 30,
        "ar_title": "الطارق",
        "pr_title": "Roƴoore",
        "ayat_number": 17,
        "ayat_img": require("./images/ayat/17.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/86_AlTariq.mp3",
        "page_number": 86,
        "size": 2304,
        "ayats_list": require("./ayats/86-at-taariq")
    },
    {
        "surat_number": 87,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الأعلى Simoore Toowal",
        "juzz_number": 30,
        "ar_title": "الأعلى",
        "pr_title": "Toowal",
        "ayat_number": 19,
        "ayat_img": require("./images/ayat/19.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/87_AlAlah.mp3",
        "page_number": 87,
        "size": 2444,
        "ayats_list": require("./ayats/87-al-alaa")
    },
    {
        "surat_number": 88,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الغاشية Simoore Soomoore",
        "juzz_number": 30,
        "ar_title": "الغاشية",
        "pr_title": "Soomoore/hippoore",
        "ayat_number": 26,
        "ayat_img": require("./images/ayat/26.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/88_AlGhachiyah.mp3",
        "page_number": 88,
        "size": 3288,
        "ayats_list": require("./ayats/88-al-ghaasiyah")
    },
    {
        "surat_number": 89,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الفجر Simoore Weetndooga",
        "juzz_number": 30,
        "ar_title": "الفجر",
        "pr_title": "Weetndooga",
        "ayat_number": 30,
        "ayat_img": require("./images/ayat/30.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/89_AlFajr.mp3",
        "page_number": 89,
        "size": 4504,
        "ayats_list": require("./ayats/89-al-fajr")
    },
    {
        "surat_number": 90,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة البلد Simoore Wuro",
        "juzz_number": 30,
        "ar_title": "البلد",
        "pr_title": "Wuro",
        "ayat_number": 20,
        "ayat_img": require("./images/ayat/20.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/90_AlBalad.mp3",
        "page_number": 90,
        "size": 2708,
        "ayats_list": require("./ayats/90-al-balad")
    },
    {
        "surat_number": 91,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الشمس Simoore Naange",
        "juzz_number": 30,
        "ar_title": "الشمس",
        "pr_title": "Naange",
        "ayat_number": 15,
        "ayat_img": require("./images/ayat/15.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/91_AlAchchams.mp3",
        "page_number": 91,
        "size": 2060,
        "ayats_list": require("./ayats/91-as-shams")
    },
    {
        "surat_number": 92,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الليل Simoore Jamma",
        "juzz_number": 30,
        "ar_title": "الليل",
        "pr_title": "Jamma",
        "ayat_number": 21,
        "ayat_img": require("./images/ayat/21.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/92_AlLail.mp3",
        "page_number": 92,
        "size": 2648,
        "ayats_list": require("./ayats/92-al-leyl")
    },
    {
        "surat_number": 93,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الضحى Simoore Beete",
        "juzz_number": 30,
        "ar_title": "الضحى",
        "pr_title": "Beete",
        "ayat_number": 11,
        "ayat_img": require("./images/ayat/11.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/93_AlDouha.mp3",
        "page_number": 93,
        "size": 1512,
        "ayats_list": require("./ayats/93-ad-duha")
    },
    {
        "surat_number": 94,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الشرح Simoore Sukkitoore",
        "juzz_number": 30,
        "ar_title": "الشرح",
        "pr_title": "Sukkitoore",
        "ayat_number": 8,
        "ayat_img": require("./images/ayat/8.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/94_AlAchcharh.mp3",
        "page_number": 94,
        "size": 984,
        "ayats_list": require("./ayats/94-as-sarh")
    },
    {
        "surat_number": 95,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة التين Simoore Lekki Tiini",
        "juzz_number": 30,
        "ar_title": "التين",
        "pr_title": "Lekki Tiini",
        "ayat_number": 8,
        "ayat_img": require("./images/ayat/8.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/95_ATTin.mp3",
        "page_number": 95,
        "size": 1316,
        "ayats_list": require("./ayats/95-at-tiin")
    },
    {
        "surat_number": 96,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة العلق Simoore Heɗɗere",
        "juzz_number": 30,
        "ar_title": "العلق",
        "pr_title": "Heɗɗere",
        "ayat_number": 19,
        "ayat_img": require("./images/ayat/19.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/96_AlAlaq.mp3",
        "page_number": 96,
        "size": 2316,
        "ayats_list": require("./ayats/96-al-alaq")
    },
    {
        "surat_number": 97,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة القدر Simoore Hoddiro",
        "juzz_number": 30,
        "ar_title": "القدر",
        "pr_title": "Hoddiro",
        "ayat_number": 5,
        "ayat_img": require("./images/ayat/5.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/97_AlQadr.mp3",
        "page_number": 97,
        "size": 1024,
        "ayats_list": require("./ayats/97-al-qadr")
    },
    {
        "surat_number": 98,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة البينة Simoore Feññinoore",
        "juzz_number": 30,
        "ar_title": "البينة",
        "pr_title": "Feññinoore",
        "ayat_number": 8,
        "ayat_img": require("./images/ayat/8.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/98_AlBaiyinah.mp3",
        "page_number": 98,
        "size": 3000,
        "ayats_list": require("./ayats/98-al-bayinnah")
    },
    {
        "surat_number": 99,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الزلزلة Simoore Jerɓugol",
        "juzz_number": 30,
        "ar_title": "الزلزلة",
        "pr_title": "Jerɓugol",
        "ayat_number": 8,
        "ayat_img": require("./images/ayat/8.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/99_AlZalzalah.mp3 ",
        "page_number": 99,
        "size": 1288,
        "ayats_list": require("./ayats/99-az-zalzalah")
    },
    {
        "surat_number": 100,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة العاديات Simoore Dogooji",
        "juzz_number": 30,
        "ar_title": "العاديات",
        "pr_title": "Dogooji",
        "ayat_number": 11,
        "ayat_img": require("./images/ayat/10.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/100_AlAdiyat.mp3",
        "page_number": 100,
        "size": 1412,
        "ayats_list": require("./ayats/100-al-adiyat")
    },
    {
        "surat_number": 101,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة القارعة Simoore Duɗɗoore",
        "juzz_number": 30,
        "ar_title": "القارعة",
        "pr_title": "Duɗɗoore",
        "ayat_number": 11,
        "ayat_img": require("./images/ayat/10.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/101_AlQariah.mp3",
        "page_number": 101,
        "size": 1328,
        "ayats_list": require("./ayats/101-al-qaria")
    },
    {
        "surat_number": 102,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة التكاثر Simoore Ɓuraa-ɓuraa",
        "juzz_number": 30,
        "ar_title": "التكاثر",
        "pr_title": "Ɓuraa-ɓuraa",
        "ayat_number": 8,
        "ayat_img": require("./images/ayat/8.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/102_AtTakasour.mp3",
        "page_number": 102,
        "size": 1188,
        "ayats_list": require("./ayats/102-at-takaashur")
    },
    {
        "surat_number": 103,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة العصر Simoore Tumaare",
        "juzz_number": 30,
        "ar_title": "العصر",
        "pr_title": "Tumaare",
        "ayat_number": 3,
        "ayat_img": require("./images/ayat/3.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/103_AlAsr.mp3",
        "page_number": 103,
        "size": 572,
        "ayats_list": require("./ayats/103-al-asr")
    },
    {
        "surat_number": 104,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الهمزة Simoore Ñohooɓe",
        "juzz_number": 30,
        "ar_title": "الهمزة",
        "pr_title": "Ñohooɓe",
        "ayat_number": 9,
        "ayat_img": require("./images/ayat/9.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/104_AlHumazah.mp3",
        "page_number": 104,
        "size": 1140,
        "ayats_list": require("./ayats/104-al-humazah")
    },
    {
        "surat_number": 105,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الفيل Simoore Ñiiwa",
        "juzz_number": 30,
        "ar_title": "الفيل",
        "pr_title": "Ñiiwa",
        "ayat_number": 5,
        "ayat_img": require("./images/ayat/5.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/105_AlFil.mp3",
        "page_number": 105,
        "size": 824,
        "ayats_list": require("./ayats/105-al-fiil")
    },
    {
        "surat_number": 106,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة قريش Simoore Khuraysiyaŋkooɓe",
        "juzz_number": 30,
        "ar_title": "قريش",
        "pr_title": "Khuraysiyaŋkooɓe",
        "ayat_number": 4,
        "ayat_img": require("./images/ayat/4.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/106_Qourach.mp3",
        "page_number": 106,
        "size": 780,
        "ayats_list": require("./ayats/106-quraysh")
    },
    {
        "surat_number": 107,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الماعون Simoore Genduɗe",
        "juzz_number": 30,
        "ar_title": "الماعون",
        "pr_title": "Genduɗe/Kuutorɗe",
        "ayat_number": 7,
        "ayat_img": require("./images/ayat/7.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/107_AlMahoun.mp3",
        "page_number": 107,
        "size": 1020,
        "ayats_list": require("./ayats/107-al-mauun")
    },
    {
        "surat_number": 108,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الكوثر Simoore Weendu Kawsara",
        "juzz_number": 30,
        "ar_title": "الكوثر",
        "pr_title": "Weendu Kawsara",
        "ayat_number": 3,
        "ayat_img": require("./images/ayat/3.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/108_AlKawsar.mp3",
        "page_number": 108,
        "size": 504,
        "ayats_list": require("./ayats/108-al-kawshar")
    },
    {
        "surat_number": 109,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الكافرون Simoore Yedduɓe",
        "juzz_number": 30,
        "ar_title": "الكافرون",
        "pr_title": "Yedduɓe",
        "ayat_number": 6,
        "ayat_img": require("./images/ayat/6.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/109_AlKafiroun.mp3",
        "page_number": 109,
        "size": 1104,
        "ayats_list": require("./ayats/109-al-kaafiruun")
    },
    {
        "surat_number": 110,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة النصر Simoore Ballal",
        "juzz_number": 30,
        "ar_title": "النصر",
        "pr_title": "Faabu/Ballal",
        "ayat_number": 3,
        "ayat_img": require("./images/ayat/3.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/110_AnNasr.mp3",
        "page_number": 110,
        "size": 764,
        "ayats_list": require("./ayats/110-an-nasr")
    },
    {
        "surat_number": 111,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة المسد Simoore Baaji",
        "juzz_number": 30,
        "ar_title": "المسد",
        "pr_title": "Baaji",
        "ayat_number": 5,
        "ayat_img": require("./images/ayat/5.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/111_AlMasad.mp3",
        "page_number": 111,
        "size": 804,
        "ayats_list": require("./ayats/111-al-masad")
    },
    {
        "surat_number": 112,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الإخلاص Simoore Laɓɓinoore",
        "juzz_number": 30,
        "ar_title": "الإخلاص",
        "pr_title": "Laɓɓinoore",
        "ayat_number": 4,
        "ayat_img": require("./images/ayat/4.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/112_AlIkhlas.mp3",
        "page_number": 112,
        "size": 504,
        "ayats_list": require("./ayats/112-al-ikhlaas")
    },
    {
        "surat_number": 113,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الفلق Simoore Weetndooga",
        "juzz_number": 30,
        "ar_title": "الفلق",
        "pr_title": "Weetndooga",
        "ayat_number": 5,
        "ayat_img": require("./images/ayat/5.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/113_AlFalaq.mp3",
        "page_number": 113,
        "size": 684,
        "ayats_list": require("./ayats/113-al-falaq")
    },
    {
        "surat_number": 114,
        "juzz": "الجزء Tumbutere 30",
        "surat": "سورة الناس Simoore Yimɓe",
        "juzz_number": 30,
        "ar_title": "الناس",
        "pr_title": "Yimɓe",
        "ayat_number": 6,
        "ayat_img": require("./images/ayat/6.png"),
        "ayat_url": "http://146.190.150.139:8080/downloads/quran/114_AnNas.mp3",
        "page_number": 114,
        "size": 864,
        "ayats_list": require("./ayats/114-an-naas")
    },
]
